### ISSUE TITLE
Исправить стили и верстку в соответствии с кол-вом сигналов

### ISSUE THREAD

**Issue by Nedgeva** [vskuzmin28/belaes-ems#1]
```
Шкаф 1
  ламп: 14;
  контакторов: 32;
Шкаф 2
  ламп: 8;
  контакторов: 32;
Шкаф 4:
  ламп: 7;
  контакторов: 20.
```

Сигналы от пульта пока оставить как есть.
Желательно поменять только стили, не затрагивая при этом разметку.
Как вариант - просто уменьшить размеры сигналов и областей, содержащих их.

**Comment by vskuzmin28** [comment]
Исправлено!
